/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness and database connectivity check */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Service is reachable. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Health"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List projects */
    get: {
      parameters: {
        query?: {
          limit?: number;
          offset?: number | null;
          status?: components["schemas"]["PublishStatus"];
          featured?: "true" | "false";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A page of projects. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProjectList"];
          };
        };
      };
    };
    put?: never;
    /** Create a project */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateProject"];
        };
      };
      responses: {
        /** @description The created project. */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Project"];
          };
        };
        /** @description Authentication required. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description A project with that slug already exists. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch a single project by slug */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The requested project. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Project"];
          };
        };
        /** @description No project with that slug. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/posts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List posts (summaries, without the body) */
    get: {
      parameters: {
        query?: {
          limit?: number;
          offset?: number | null;
          status?: components["schemas"]["PublishStatus"];
          tag?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A page of post summaries. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PostList"];
          };
        };
      };
    };
    put?: never;
    /** Create a post */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreatePost"];
        };
      };
      responses: {
        /** @description The created post. */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Post"];
          };
        };
        /** @description Authentication required. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description A post with that slug already exists. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/posts/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch a single post by slug, including its Markdown body */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The requested post. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Post"];
          };
        };
        /** @description No post with that slug. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Health: {
      /** @enum {string} */
      status: "ok" | "degraded";
      /** @enum {string} */
      database: "up" | "down";
      uptimeSeconds: number;
    };
    ProjectList: {
      items: components["schemas"]["Project"][];
      /** @example 42 */
      total: number;
      /** @example 20 */
      limit: number;
      /** @example 0 */
      offset: number;
    };
    Project: {
      /** Format: uuid */
      id: string;
      /** @example devcroaker */
      slug: string;
      /** @example devCroaker */
      title: string;
      /** @example Personal site and reference implementation. */
      summary: string;
      description: string | null;
      /** Format: uri */
      repoUrl: string | null;
      /** Format: uri */
      liveUrl: string | null;
      /**
       * @example [
       *       "TypeScript",
       *       "AWS CDK"
       *     ]
       */
      techStack: string[];
      status: components["schemas"]["PublishStatus"];
      featured: boolean;
      sortOrder: number;
      /** Format: date-time */
      publishedAt: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @enum {string} */
    PublishStatus: "draft" | "published" | "archived";
    Error: {
      error: {
        /** @example not_found */
        code: string;
        /** @example Project not found */
        message: string;
      };
    };
    CreateProject: {
      /** @example devcroaker */
      slug: string;
      /** @example devCroaker */
      title: string;
      /** @example Personal site and reference implementation. */
      summary: string;
      description?: string | null;
      /** Format: uri */
      repoUrl?: string | null;
      /** Format: uri */
      liveUrl?: string | null;
      /**
       * @example [
       *       "TypeScript",
       *       "AWS CDK"
       *     ]
       */
      techStack?: string[];
      status?: components["schemas"]["PublishStatus"];
      featured?: boolean;
      sortOrder?: number;
      /** Format: date-time */
      publishedAt?: string | null;
    };
    PostList: {
      items: components["schemas"]["PostSummary"][];
      /** @example 42 */
      total: number;
      /** @example 20 */
      limit: number;
      /** @example 0 */
      offset: number;
    };
    PostSummary: {
      /** Format: uuid */
      id: string;
      /** @example building-a-cheap-aws-stack */
      slug: string;
      title: string;
      excerpt: string | null;
      status: components["schemas"]["PublishStatus"];
      /** Format: uuid */
      authorId: string | null;
      tags: components["schemas"]["Tag"][];
      /** Format: date-time */
      publishedAt: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    Tag: {
      /** Format: uuid */
      id: string;
      /** @example aws */
      slug: string;
      /** @example AWS */
      name: string;
    };
    Post: {
      /** Format: uuid */
      id: string;
      /** @example building-a-cheap-aws-stack */
      slug: string;
      title: string;
      excerpt: string | null;
      /** @description Markdown source. */
      body: string;
      status: components["schemas"]["PublishStatus"];
      /** Format: uuid */
      authorId: string | null;
      tags: components["schemas"]["Tag"][];
      /** Format: date-time */
      publishedAt: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreatePost: {
      /** @example building-a-cheap-aws-stack */
      slug: string;
      title: string;
      excerpt?: string | null;
      /** @description Markdown source. */
      body: string;
      status?: components["schemas"]["PublishStatus"];
      /** Format: uuid */
      authorId?: string | null;
      /** Format: date-time */
      publishedAt?: string | null;
      tagSlugs?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
